# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_DATABASE: medical_db
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: testuser
          MYSQL_PASSWORD: password
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up MySQL Database
      run: |
        mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'password';"
        mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "DROP DATABASE IF EXISTS medical_db;"
        mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "CREATE DATABASE medical_db;"
        mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "GRANT ALL ON medical_db.* TO 'testuser'@'localhost';"
    - name: Build and run Unit Tests with Maven
      run: mvn -B package --file pom.xml spotbugs:spotbugs checkstyle:checkstyle -Dstart-class=com.symbolic.symbolic.SymbolicApplication -Dgroups="UnitTest"

    - name: Build and run Integration Tests with Maven
      run: mvn -B package --file pom.xml spotbugs:spotbugs checkstyle:checkstyle -Dstart-class=com.symbolic.symbolic.SymbolicApplication -Dgroups="IntegrationTest"

    - name: jacoco-reporter
      # You may pin to the exact commit or the version.
      # uses: PavanMudigonda/jacoco-reporter@76044ebc031589dcbce0bb1048ffee1072a43f97
      uses: PavanMudigonda/jacoco-reporter@v4.9
      with:
        # Path to the JaCoCo coverage results file which will be used to generate a report. The only coverage results format supported is the JaCoCo XML schema.
        coverage_results_path: target/site/jacoco/jacoco.xml
        # GITHUB_TOKEN to authenticate against API calls to attach report to Workflow Run.
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Push SpotBugs report
      # You may pin to the exact commit or the version.
      # uses: jwgmeligmeyling/spotbugs-github-action@b8e2c3523acb34c87f14e18cbcd2d87db8c8584e
      uses: jwgmeligmeyling/spotbugs-github-action@v1.2
      with:
        # A file, directory or wildcard pattern that describes where to find the reports
        path: target/spotbugsXml.xml
        # Check run name under which the report is created
        # name: # optional, default is spotbugs
        # Check run title under which the report is created
        # title: # optional, default is SpotBugs Source Code Analyzer report
        # Personal access token (PAT) used to fetch the repository. The PAT is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the PAT. We recommend using a service account with the least permissions necessary. Also when generating a new PAT, select the least scopes necessary. [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Checkstyle report
      # You may pin to the exact commit or the version.
      # uses: jwgmeligmeyling/checkstyle-github-action@50292990e18466f2c5d95d04ff5fab931254fa5f
      uses: jwgmeligmeyling/checkstyle-github-action@v1.2
      continue-on-error: true
      with:
        # A file, directory or wildcard pattern that describes where to find the reports
        path: target/checkstyle-result.xml
        # Check run name under which the report is created
        # name: # optional, default is Checkstyle
        # Check run title under which the report is created
        # title: # optional, default is Checkstyle report
        # Personal access token (PAT) used to fetch the repository. The PAT is configured with the local git config, which enables your scripts to run authenticated git commands. The post-job step removes the PAT. We recommend using a service account with the least permissions necessary. Also when generating a new PAT, select the least scopes necessary. [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
        token: ${{ secrets.GITHUB_TOKEN }}

  run_live_tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_DATABASE: medical_db
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: testuser
          MYSQL_PASSWORD: password
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Set up MySQL Database
      run: |
        mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'password';"
        mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "DROP DATABASE IF EXISTS medical_db;"
        mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "CREATE DATABASE medical_db;"
        mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "GRANT ALL ON medical_db.* TO 'testuser'@'localhost';"
    # Install Node on the runner
    # - name: Install Node
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: "16.x"

    # # Install the newman command line utility and also install the html extra reporter
    # - name: Install newman
    #   run: |
    #     npm install -g newman
    #     npm install -g newman-reporter-htmlextra

    # - name: Create results directory
    #   run: mkdir -p testResults
    
    - name: Run Symbolic Application
      run: |
        mvn -B package --file pom.xml spring-boot:run -Dstart-class=com.symbolic.symbolic.SymbolicApplication -Dgroups="UnitTest" &
        for attempt in {1..120}; do sleep 1; if curl --location 'http://127.0.0.1:8080/api/client/authenticate' --header 'Content-Type: application/json' --data '{"name": "admin"}' --output /dev/null --silent; then echo ready; break; fi; echo waiting on launch...; done
    # # Run the POSTMAN collection
    # - name: Run Postman collection
    #   run: |
    #     newman run postman/collections/BaseRequestTests.postman_collection.json -e postman/environments/CIEnvironment.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

    # # Upload the contents of Test Results directory to workspace
    # - name: Upload the Postman run results
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: PostmanAPITests
    #     path: testResults
    - name: Configure DB Test User
      run: |
        mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e "USE medical_db; INSERT INTO user \n values (1, NULL, 'admin', '\$2a\$10\$WZ.eH3iwwNHlOe80trnazeG0s3l6RFxvP5zIuk5yMTecIWNg2tXrO', 'ADMIN');"
        
    - name: Build and run Client Tests with Maven
      run: mvn -B package --file pom.xml -Dstart-class=com.symbolic.symbolic.ClientApplication -Dgroups="ClientTest"

    - name: Postman API Tests with Newman
      # You may pin to the exact commit or the version.
      # uses: matt-ball/newman-action@170d252f10d199d75d6be4c739b48a3bd5f15ece
      uses: matt-ball/newman-action@v2.0.0
      with:
        # Collection to use
        collection: postman/collections/BaseRequestTests.postman_collection.json
        # Environment to use
        environment: postman/environments/CIEnvironment.postman_environment.json

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
